services:
  businesshostdatabase:
    image: sqlserver-with-tools
    ports:
      - "8010:1433"  
    environment:
      SA_PASSWORD: "BusinessHost!Passw0rd"
      DATABASE_NAME: "BusinessHost"
      API_ENVIRONMENT: "LOCAL"
    volumes:
      - ./dacpac/Edrington.BuinsessService.Database.dacpac:/tmp/your-dacpac-file.dacpac
      - ./EmptyDatabase/entrypoint.sh:/tmp/entrypoint.sh
    command: /tmp/entrypoint.sh

  consumerapidatabase:
    image: sqlserver-with-tools
    ports:
      - "8020:1433"
    environment:
      SA_PASSWORD: "GatewayApi!Passw0rd"
      DATABASE_NAME: "GatewayApi"
      API_ENVIRONMENT: "LOCAL"
    volumes:
      - ./dacpac/Edrington.Api.Database.dacpac:/tmp/your-dacpac-file.dacpac
      - ./EmptyDatabase/entrypoint.sh:/tmp/entrypoint.sh
    command: /tmp/entrypoint.sh
    